# Common logging config
log_level: info
log_filters: ""
log_json: false
log_thread_id: false

# Mode of operation
mode: cli

# Where the user-owned content should live
ragnardoc_home: ~/.ragnardoc

# Document scraping config
scraping:
  # Root directories for scraping
  roots: []
  # File extensions indicating raw text
  raw_text_extensions:
    - md
    - txt
    - json
    - yaml
  # Which docs to include in the scrape
  include:
    paths: []
    regexprs: []
  # Which docs to exclude in the scrape
  exclude:
    paths: []
    regexprs: []

# Document ingestion config
ingestion:
  # Factory list of ingestion plugins to ingest to
  plugins: []

# State storage
storage:
  type: sqlite
  config:
    # Any non-absolute path will be prepended with ragnardoc_home
    db_path: storage.db
